const classes = [
  'bg-indigo-lightest', 'bg-indigo-light', 'bg-indigo', 'bg-indigo-dark', 'bg-indigo-darkest',
  'border-indigo-lightest', 'border-indigo-light', 'border-indigo', 'border-indigo-dark', 'border-indigo-darkest',
  'text-indigo-lightest', 'text-indigo-light', 'text-indigo', 'text-indigo-dark', 'text-indigo-darkest',
  'hover:bg-indigo-lightest', 'hover:bg-indigo-light', 'hover:bg-indigo', 'hover:bg-indigo-dark', 'hover:bg-indigo-darkest',
  'hover:border-indigo-lightest', 'hover:border-indigo-light', 'hover:border-indigo', 'hover:border-indigo-dark', 'hover:border-indigo-darkest',
  'hover:text-indigo-lightest', 'hover:text-indigo-light', 'hover:text-indigo', 'hover:text-indigo-dark', 'hover:text-indigo-darkest',
  'focus:ring-indigo-lightest', 'focus:ring-indigo-light', 'focus:ring-indigo', 'focus:ring-indigo-dark', 'focus:ring-indigo-darkest',
  
  'bg-sky-lightest', 'bg-sky-light', 'bg-sky', 'bg-sky-dark', 'bg-sky-darkest',
  'border-sky-lightest', 'border-sky-light', 'border-sky', 'border-sky-dark', 'border-sky-darkest',
  'text-sky-lightest', 'text-sky-light', 'text-sky', 'text-sky-dark', 'text-sky-darkest',
  'hover:bg-sky-lightest', 'hover:bg-sky-light', 'hover:bg-sky', 'hover:bg-sky-dark', 'hover:bg-sky-darkest',
  'hover:border-sky-lightest', 'hover:border-sky-light', 'hover:border-sky', 'hover:border-sky-dark', 'hover:border-sky-darkest',
  'hover:text-sky-lightest', 'hover:text-sky-light', 'hover:text-sky', 'hover:text-sky-dark', 'hover:text-sky-darkest',
  'focus:ring-sky-lightest', 'focus:ring-sky-light', 'focus:ring-sky', 'focus:ring-sky-dark', 'focus:ring-sky-darkest',

  'bg-steel-lightest', 'bg-steel-light', 'bg-steel', 'bg-steel-dark', 'bg-steel-darkest',
  'border-steel-lightest', 'border-steel-light', 'border-steel', 'border-steel-dark', 'border-steel-darkest',
  'text-steel-lightest', 'text-steel-light', 'text-steel', 'text-steel-dark', 'text-steel-darkest',
  'hover:bg-steel-lightest', 'hover:bg-steel-light', 'hover:bg-steel', 'hover:bg-steel-dark', 'hover:bg-steel-darkest',
  'hover:border-steel-lightest', 'hover:border-steel-light', 'hover:border-steel', 'hover:border-steel-dark', 'hover:border-steel-darkest',
  'hover:text-steel-lightest', 'hover:text-steel-light', 'hover:text-steel', 'hover:text-steel-dark', 'hover:text-steel-darkest',
  'focus:ring-steel-lightest', 'focus:ring-steel-light', 'focus:ring-steel', 'focus:ring-steel-dark', 'focus:ring-steel-darkest',
  
  'bg-success-lightest', 'bg-success-light', 'bg-success', 'bg-success-dark', 'bg-success-darkest',
  'border-success-lightest', 'border-success-light', 'border-success', 'border-success-dark', 'border-success-darkest',
  'text-success-lightest', 'text-success-light', 'text-success', 'text-success-dark', 'text-success-darkest',
  'hover:bg-success-lightest', 'hover:bg-success-light', 'hover:bg-success', 'hover:bg-success-dark', 'hover:bg-success-darkest',
  'hover:border-success-lightest', 'hover:border-success-light', 'hover:border-success', 'hover:border-success-dark', 'hover:border-success-darkest',
  'hover:text-success-lightest', 'hover:text-success-light', 'hover:text-success', 'hover:text-success-dark', 'hover:text-success-darkest',
  'focus:ring-success-lightest', 'focus:ring-success-light', 'focus:ring-success', 'focus:ring-success-dark', 'focus:ring-success-darkest',
  
  'bg-warning-lightest', 'bg-warning-light', 'bg-warning', 'bg-warning-dark', 'bg-warning-darkest',
  'border-warning-lightest', 'border-warning-light', 'border-warning', 'border-warning-dark', 'border-warning-darkest',
  'text-warning-lightest', 'text-warning-light', 'text-warning', 'text-warning-dark', 'text-warning-darkest',
  'hover:bg-warning-lightest', 'hover:bg-warning-light', 'hover:bg-warning', 'hover:bg-warning-dark', 'hover:bg-warning-darkest',
  'hover:border-warning-lightest', 'hover:border-warning-light', 'hover:border-warning', 'hover:border-warning-dark', 'hover:border-warning-darkest',
  'hover:text-warning-lightest', 'hover:text-warning-light', 'hover:text-warning', 'hover:text-warning-dark', 'hover:text-warning-darkest',
  'focus:ring-warning-lightest', 'focus:ring-warning-light', 'focus:ring-warning', 'focus:ring-warning-dark', 'focus:ring-warning-darkest',
  
  'bg-danger-lightest', 'bg-danger-light', 'bg-danger', 'bg-danger-dark', 'bg-danger-darkest',
  'border-danger-lightest', 'border-danger-light', 'border-danger', 'border-danger-dark', 'border-danger-darkest',
  'text-danger-lightest', 'text-danger-light', 'text-danger', 'text-danger-dark', 'text-danger-darkest',
  'hover:bg-danger-lightest', 'hover:bg-danger-light', 'hover:bg-danger', 'hover:bg-danger-dark', 'hover:bg-danger-darkest',
  'hover:border-danger-lightest', 'hover:border-danger-light', 'hover:border-danger', 'hover:border-danger-dark', 'hover:border-danger-darkest',
  'hover:text-danger-lightest', 'hover:text-danger-light', 'hover:text-danger', 'hover:text-danger-dark', 'hover:text-danger-darkest',
  'focus:ring-danger-lightest', 'focus:ring-danger-light', 'focus:ring-danger', 'focus:ring-danger-dark', 'focus:ring-danger-darkest',
]
