name: Deploy application documentation to Azure SWA

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    if: ${{ startsWith(github.event.head_commit.message, 'docs:') }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build and Deploy Job
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DOCS_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          app_build_command: "npm run build-storybook"
          output_location: "/storybook-static"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
